name: grafana-otel

services:
  loki:
    image: grafana/loki:3.5.8
    ports:
      - "3100:3100"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - loki-data:/loki/
      - ./.config/loki-config.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:2.9.0
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./.config/tempo.yaml:/etc/tempo.yaml:ro
      - tempo-data:/var/tempo
  #    ports:
  #      - "14268:14268" # jaeger ui
  #      - "3200:3200"   # tempo      
  #      - "4317:4317"  # otlp grpc
  #      - "4318:4318"  # otlp http
  
  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus
    ports:
      - "9090:9090"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ./.config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:12.1.0
    container_name: grafana
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana/
      - ./.config/ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml
      - ./.config/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./pharse1/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
  
  otel-collector:
    container_name: otelcollector
    image: otel/opentelemetry-collector-contrib:0.140.0
    command: [ --config=/etc/otel-collector-config.yml ]
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./.config/otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    depends_on:
      loki:
        condition: service_started
      tempo:
        condition: service_started
      prometheus:
        condition: service_started
    restart: unless-stopped
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      #   - 1888:1888 # pprof extension
      #   - 8888:8888 # Prometheus metrics exposed by the collector for itself
      #   - 8889:8889 # Prometheus exporter metrics for applications
      #   - 13133:13133 # health_check extension      
      #   - 55679:55679 # zpages extension

networks:
  default:
    name: otel-network
    driver: bridge

volumes:
  loki-data:
  prometheus-data:
  grafana-data:
  tempo-data: